"""feature_daily.industry_trend_score（產業趨勢分數）

Revision ID: 1792070d957a
Revises: 62ea86a2d817
Create Date: 2026-09-09 04:29:32.695380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1792070d957a'
down_revision: Union[str, Sequence[str], None] = '62ea86a2d817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_daily', sa.Column('industry_trend_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_daily', 'industry_trend_score')
    # ### end Alembic commands ###
