"""futures_daily（TAIFEX 台指期每日行情）

Revision ID: 19e933bc4c07
Revises: a1b2c3d4e5f6
Create Date: 2026-09-17 20:58:17.272139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '19e933bc4c07'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('futures_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract', sa.String(length=8), nullable=False),
    sa.Column('contract_month', sa.String(length=16), nullable=False),
    sa.Column('open', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('change', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('settlement_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('open_interest', sa.BigInteger(), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract', 'contract_month', 'data_date', name='uq_futures_daily')
    )
    op.create_index(op.f('ix_futures_daily_data_date'), 'futures_daily', ['data_date'], unique=False)
    op.create_index(op.f('ix_futures_daily_updated_at'), 'futures_daily', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_futures_daily_updated_at'), table_name='futures_daily')
    op.drop_index(op.f('ix_futures_daily_data_date'), table_name='futures_daily')
    op.drop_table('futures_daily')
    # ### end Alembic commands ###
