"""initial schema

Revision ID: 256efb931d6e
Revises: 
Create Date: 2026-09-06 09:25:12.262396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '256efb931d6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('industry', sa.String(length=32), nullable=True),
    sa.Column('shares_outstanding', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('daily_price',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('open', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('turnover', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stock.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'data_date', name='uq_daily_price')
    )
    op.create_index(op.f('ix_daily_price_data_date'), 'daily_price', ['data_date'], unique=False)
    op.create_index(op.f('ix_daily_price_symbol'), 'daily_price', ['symbol'], unique=False)
    op.create_table('feature_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('close', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('atr14', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('ma20', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('recent_swing_low', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('turnover', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('close_vs_ma20_pct', sa.Float(), nullable=True),
    sa.Column('close_vs_vwap_pct', sa.Float(), nullable=True),
    sa.Column('foreign_5d_z', sa.Float(), nullable=True),
    sa.Column('trust_5d_z', sa.Float(), nullable=True),
    sa.Column('dealer_5d_z', sa.Float(), nullable=True),
    sa.Column('margin_balance_change_z', sa.Float(), nullable=True),
    sa.Column('short_balance_change_z', sa.Float(), nullable=True),
    sa.Column('sbl_change_z', sa.Float(), nullable=True),
    sa.Column('large_holder_ratio_change_z', sa.Float(), nullable=True),
    sa.Column('retail_holder_ratio_change_z', sa.Float(), nullable=True),
    sa.Column('holder_count_change_z', sa.Float(), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stock.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'data_date', name='uq_feature_daily')
    )
    op.create_index(op.f('ix_feature_daily_data_date'), 'feature_daily', ['data_date'], unique=False)
    op.create_index(op.f('ix_feature_daily_symbol'), 'feature_daily', ['symbol'], unique=False)
    op.create_table('institutional_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('foreign_net', sa.BigInteger(), nullable=True),
    sa.Column('trust_net', sa.BigInteger(), nullable=True),
    sa.Column('dealer_self_net', sa.BigInteger(), nullable=True),
    sa.Column('dealer_hedge_net', sa.BigInteger(), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stock.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'data_date', name='uq_institutional_daily')
    )
    op.create_index(op.f('ix_institutional_daily_data_date'), 'institutional_daily', ['data_date'], unique=False)
    op.create_index(op.f('ix_institutional_daily_symbol'), 'institutional_daily', ['symbol'], unique=False)
    op.create_table('margin_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('margin_buy', sa.Integer(), nullable=True),
    sa.Column('margin_sell', sa.Integer(), nullable=True),
    sa.Column('margin_balance', sa.Integer(), nullable=True),
    sa.Column('short_sell', sa.Integer(), nullable=True),
    sa.Column('short_cover', sa.Integer(), nullable=True),
    sa.Column('short_balance', sa.Integer(), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stock.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'data_date', name='uq_margin_daily')
    )
    op.create_index(op.f('ix_margin_daily_data_date'), 'margin_daily', ['data_date'], unique=False)
    op.create_index(op.f('ix_margin_daily_symbol'), 'margin_daily', ['symbol'], unique=False)
    op.create_table('sbl_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('sbl_short_sell', sa.BigInteger(), nullable=True),
    sa.Column('sbl_return', sa.BigInteger(), nullable=True),
    sa.Column('sbl_balance', sa.BigInteger(), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stock.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'data_date', name='uq_sbl_daily')
    )
    op.create_index(op.f('ix_sbl_daily_data_date'), 'sbl_daily', ['data_date'], unique=False)
    op.create_index(op.f('ix_sbl_daily_symbol'), 'sbl_daily', ['symbol'], unique=False)
    op.create_table('signal_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('chip_score', sa.Float(), nullable=False),
    sa.Column('intraday_score', sa.Float(), nullable=True),
    sa.Column('institutional_score', sa.Float(), nullable=True),
    sa.Column('holder_score', sa.Float(), nullable=True),
    sa.Column('market_score', sa.Float(), nullable=True),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('entry_low', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('entry_high', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('tp1', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('tp2', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('risk_reward', sa.Float(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stock.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'data_date', name='uq_signal_snapshot')
    )
    op.create_index(op.f('ix_signal_snapshot_data_date'), 'signal_snapshot', ['data_date'], unique=False)
    op.create_index(op.f('ix_signal_snapshot_symbol'), 'signal_snapshot', ['symbol'], unique=False)
    op.create_table('tdcc_summary_weekly',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('retail_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('medium_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('large_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('super_large_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('holder_count', sa.Integer(), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stock.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'data_date', name='uq_tdcc_summary_weekly')
    )
    op.create_index(op.f('ix_tdcc_summary_weekly_data_date'), 'tdcc_summary_weekly', ['data_date'], unique=False)
    op.create_index(op.f('ix_tdcc_summary_weekly_symbol'), 'tdcc_summary_weekly', ['symbol'], unique=False)
    op.create_table('tdcc_weekly',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('holder_count', sa.Integer(), nullable=True),
    sa.Column('shares', sa.BigInteger(), nullable=True),
    sa.Column('ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stock.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'data_date', 'level', name='uq_tdcc_weekly')
    )
    op.create_index(op.f('ix_tdcc_weekly_data_date'), 'tdcc_weekly', ['data_date'], unique=False)
    op.create_index(op.f('ix_tdcc_weekly_symbol'), 'tdcc_weekly', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tdcc_weekly_symbol'), table_name='tdcc_weekly')
    op.drop_index(op.f('ix_tdcc_weekly_data_date'), table_name='tdcc_weekly')
    op.drop_table('tdcc_weekly')
    op.drop_index(op.f('ix_tdcc_summary_weekly_symbol'), table_name='tdcc_summary_weekly')
    op.drop_index(op.f('ix_tdcc_summary_weekly_data_date'), table_name='tdcc_summary_weekly')
    op.drop_table('tdcc_summary_weekly')
    op.drop_index(op.f('ix_signal_snapshot_symbol'), table_name='signal_snapshot')
    op.drop_index(op.f('ix_signal_snapshot_data_date'), table_name='signal_snapshot')
    op.drop_table('signal_snapshot')
    op.drop_index(op.f('ix_sbl_daily_symbol'), table_name='sbl_daily')
    op.drop_index(op.f('ix_sbl_daily_data_date'), table_name='sbl_daily')
    op.drop_table('sbl_daily')
    op.drop_index(op.f('ix_margin_daily_symbol'), table_name='margin_daily')
    op.drop_index(op.f('ix_margin_daily_data_date'), table_name='margin_daily')
    op.drop_table('margin_daily')
    op.drop_index(op.f('ix_institutional_daily_symbol'), table_name='institutional_daily')
    op.drop_index(op.f('ix_institutional_daily_data_date'), table_name='institutional_daily')
    op.drop_table('institutional_daily')
    op.drop_index(op.f('ix_feature_daily_symbol'), table_name='feature_daily')
    op.drop_index(op.f('ix_feature_daily_data_date'), table_name='feature_daily')
    op.drop_table('feature_daily')
    op.drop_index(op.f('ix_daily_price_symbol'), table_name='daily_price')
    op.drop_index(op.f('ix_daily_price_data_date'), table_name='daily_price')
    op.drop_table('daily_price')
    op.drop_table('stock')
    # ### end Alembic commands ###
