"""corporate_action (TWT49U ex-dividend/rights + adj_factor)

Revision ID: 4b75aa8390d8
Revises: e27682c77a54
Create Date: 2026-09-08 21:32:28.957905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b75aa8390d8'
down_revision: Union[str, Sequence[str], None] = 'e27682c77a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_action',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('prev_close', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('reference_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('value', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('adj_factor', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stock.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'data_date', name='uq_corporate_action')
    )
    op.create_index(op.f('ix_corporate_action_data_date'), 'corporate_action', ['data_date'], unique=False)
    op.create_index(op.f('ix_corporate_action_symbol'), 'corporate_action', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corporate_action_symbol'), table_name='corporate_action')
    op.drop_index(op.f('ix_corporate_action_data_date'), table_name='corporate_action')
    op.drop_table('corporate_action')
    # ### end Alembic commands ###
