"""market index and daily

Revision ID: 544da228bd2a
Revises: 256efb931d6e
Create Date: 2026-09-06 10:38:35.053876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544da228bd2a'
down_revision: Union[str, Sequence[str], None] = '256efb931d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('taiex_close', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('taiex_ma20', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('taiex_ma60', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ma20_slope', sa.Float(), nullable=True),
    sa.Column('advancers', sa.BigInteger(), nullable=True),
    sa.Column('decliners', sa.BigInteger(), nullable=True),
    sa.Column('volatility_pct', sa.Float(), nullable=True),
    sa.Column('market_trend_score', sa.Float(), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_date', name='uq_market_daily')
    )
    op.create_index(op.f('ix_market_daily_data_date'), 'market_daily', ['data_date'], unique=False)
    op.create_table('market_index',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('taiex_close', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('turnover', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_date', name='uq_market_index')
    )
    op.create_index(op.f('ix_market_index_data_date'), 'market_index', ['data_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_index_data_date'), table_name='market_index')
    op.drop_table('market_index')
    op.drop_index(op.f('ix_market_daily_data_date'), table_name='market_daily')
    op.drop_table('market_daily')
    # ### end Alembic commands ###
