"""corporate_action.share_factor（量還原因子）

Revision ID: 62ea86a2d817
Revises: 4b75aa8390d8
Create Date: 2026-09-09 01:17:15.833456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ea86a2d817'
down_revision: Union[str, Sequence[str], None] = '4b75aa8390d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_action', sa.Column('share_factor', sa.Numeric(precision=12, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporate_action', 'share_factor')
    # ### end Alembic commands ###
