"""feature_daily intraday z columns

Revision ID: a47768b65024
Revises: df1eab740e84
Create Date: 2026-09-06 12:10:45.275936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47768b65024'
down_revision: Union[str, Sequence[str], None] = 'df1eab740e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_daily', sa.Column('cvd_z', sa.Float(), nullable=True))
    op.add_column('feature_daily', sa.Column('large_trade_delta_z', sa.Float(), nullable=True))
    op.add_column('feature_daily', sa.Column('intraday_obi', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_daily', 'intraday_obi')
    op.drop_column('feature_daily', 'large_trade_delta_z')
    op.drop_column('feature_daily', 'cvd_z')
    # ### end Alembic commands ###
