"""add feature_daily change_pct

Revision ID: be337f887ae8
Revises: 544da228bd2a
Create Date: 2026-09-06 10:50:19.407409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be337f887ae8'
down_revision: Union[str, Sequence[str], None] = '544da228bd2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_daily', sa.Column('change_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_daily', 'change_pct')
    # ### end Alembic commands ###
