"""mops phase2 shadow tables (docs/14, shadow-only)

新增 insider_holding_monthly / insider_transfer_declaration / mops_fetch_coverage /
mops_shadow_feature_daily 四張表。只新增、不改動既有表；正式評分不讀這些表。

註：autogenerate 另偵測到 job_run.started_at、threshold_change.changed_at、
threshold_override.updated_at 的既有 nullable 漂移，與本次無關，刻意不在此處修正。

Revision ID: c9d2e7f1a3b5
Revises: b8e1f5a3c7d9
Create Date: 2026-09-13 22:21:10.520426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c9d2e7f1a3b5'
down_revision: Union[str, Sequence[str], None] = 'b8e1f5a3c7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mops_fetch_coverage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dataset', sa.String(length=32), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset', 'market', 'data_date', name='uq_mops_fetch_coverage')
    )
    op.create_table('insider_holding_monthly',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('holder_name', sa.String(length=256), nullable=False),
    sa.Column('row_seq', sa.Integer(), nullable=False),
    sa.Column('shares_at_election', sa.BigInteger(), nullable=True),
    sa.Column('current_shares', sa.BigInteger(), nullable=True),
    sa.Column('pledged_shares', sa.BigInteger(), nullable=True),
    sa.Column('pledge_pct', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('related_shares', sa.BigInteger(), nullable=True),
    sa.Column('related_pledged_shares', sa.BigInteger(), nullable=True),
    sa.Column('related_pledge_pct', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stock.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'data_date', 'source', 'report_date', 'title', 'holder_name', 'row_seq', name='uq_insider_holding_monthly')
    )
    op.create_index(op.f('ix_insider_holding_monthly_data_date'), 'insider_holding_monthly', ['data_date'], unique=False)
    op.create_index(op.f('ix_insider_holding_monthly_symbol'), 'insider_holding_monthly', ['symbol'], unique=False)
    op.create_table('insider_transfer_declaration',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('reporter_role', sa.String(length=64), nullable=False),
    sa.Column('reporter_name', sa.String(length=256), nullable=False),
    sa.Column('transfer_method', sa.String(length=128), nullable=True),
    sa.Column('method_category', sa.String(length=16), nullable=False),
    sa.Column('transfer_shares', sa.BigInteger(), nullable=True),
    sa.Column('max_intraday_shares', sa.BigInteger(), nullable=True),
    sa.Column('transferee', sa.String(length=256), nullable=True),
    sa.Column('current_own_shares', sa.BigInteger(), nullable=True),
    sa.Column('current_trust_shares', sa.BigInteger(), nullable=True),
    sa.Column('planned_own_shares', sa.BigInteger(), nullable=True),
    sa.Column('planned_trust_shares', sa.BigInteger(), nullable=True),
    sa.Column('after_own_shares', sa.BigInteger(), nullable=True),
    sa.Column('after_trust_shares', sa.BigInteger(), nullable=True),
    sa.Column('effective_start', sa.Date(), nullable=True),
    sa.Column('effective_end', sa.Date(), nullable=True),
    sa.Column('amendment_note', sa.String(length=128), nullable=True),
    sa.Column('amends_report_date', sa.Date(), nullable=True),
    sa.Column('superseded_on', sa.Date(), nullable=True),
    sa.Column('unfinished_flag', sa.String(length=8), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stock.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'data_date', 'row_hash', name='uq_insider_transfer_declaration')
    )
    op.create_index(op.f('ix_insider_transfer_declaration_data_date'), 'insider_transfer_declaration', ['data_date'], unique=False)
    op.create_index(op.f('ix_insider_transfer_declaration_symbol'), 'insider_transfer_declaration', ['symbol'], unique=False)
    op.create_index(op.f('ix_insider_transfer_declaration_updated_at'), 'insider_transfer_declaration', ['updated_at'], unique=False)
    op.create_table('mops_shadow_feature_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('holding_month', sa.Date(), nullable=True),
    sa.Column('holding_source', sa.String(length=16), nullable=True),
    sa.Column('insider_holding_change_pct', sa.Float(), nullable=True),
    sa.Column('insider_pledge_ratio', sa.Float(), nullable=True),
    sa.Column('insider_pledge_ratio_change', sa.Float(), nullable=True),
    sa.Column('major_holder_change_pct', sa.Float(), nullable=True),
    sa.Column('transfer_market_sale_ratio', sa.Float(), nullable=True),
    sa.Column('insider_holding_change_z', sa.Float(), nullable=True),
    sa.Column('insider_pledge_ratio_z', sa.Float(), nullable=True),
    sa.Column('insider_pledge_ratio_change_z', sa.Float(), nullable=True),
    sa.Column('major_holder_change_z', sa.Float(), nullable=True),
    sa.Column('transfer_market_sale_z', sa.Float(), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stock.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'data_date', name='uq_mops_shadow_feature_daily')
    )
    op.create_index(op.f('ix_mops_shadow_feature_daily_data_date'), 'mops_shadow_feature_daily', ['data_date'], unique=False)
    op.create_index(op.f('ix_mops_shadow_feature_daily_symbol'), 'mops_shadow_feature_daily', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mops_shadow_feature_daily_symbol'), table_name='mops_shadow_feature_daily')
    op.drop_index(op.f('ix_mops_shadow_feature_daily_data_date'), table_name='mops_shadow_feature_daily')
    op.drop_table('mops_shadow_feature_daily')
    op.drop_index(op.f('ix_insider_transfer_declaration_updated_at'), table_name='insider_transfer_declaration')
    op.drop_index(op.f('ix_insider_transfer_declaration_symbol'), table_name='insider_transfer_declaration')
    op.drop_index(op.f('ix_insider_transfer_declaration_data_date'), table_name='insider_transfer_declaration')
    op.drop_table('insider_transfer_declaration')
    op.drop_index(op.f('ix_insider_holding_monthly_symbol'), table_name='insider_holding_monthly')
    op.drop_index(op.f('ix_insider_holding_monthly_data_date'), table_name='insider_holding_monthly')
    op.drop_table('insider_holding_monthly')
    op.drop_table('mops_fetch_coverage')
    # ### end Alembic commands ###
