"""raw_tick index

Revision ID: df1eab740e84
Revises: 8e511c057bc9
Create Date: 2026-09-06 11:42:14.659237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df1eab740e84'
down_revision: Union[str, Sequence[str], None] = '8e511c057bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_raw_tick_symbol_date', 'raw_tick', ['symbol', 'data_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_tick_symbol_date', table_name='raw_tick')
    # ### end Alembic commands ###
