"""feature_daily intraday absorption trade_speed price_efficiency z

Revision ID: e27682c77a54
Revises: a47768b65024
Create Date: 2026-09-06 15:01:13.572629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e27682c77a54'
down_revision: Union[str, Sequence[str], None] = 'a47768b65024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_daily', sa.Column('absorption_z', sa.Float(), nullable=True))
    op.add_column('feature_daily', sa.Column('trade_speed_z', sa.Float(), nullable=True))
    op.add_column('feature_daily', sa.Column('price_efficiency_z', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_daily', 'price_efficiency_z')
    op.drop_column('feature_daily', 'trade_speed_z')
    op.drop_column('feature_daily', 'absorption_z')
    # ### end Alembic commands ###
